# Generated by Django 3.1.4 on 2020-12-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201230_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='django.jpg', upload_to='images/'),
        ),
    ]
