# Generated by Django 3.1.4 on 2020-12-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201230_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/post-bg.jpg', upload_to='images/'),
        ),
    ]
